### ISSUE TITLE
"Missing" objects?

### ISSUE THREAD

**Issue by willettk** [ttfnrob/MilkMan#15]
Curious when looking at the sample you provided http://mwp-milkman.herokuapp.com/subjects/AMW0002t4h - there seems to be at least two obvious bubbles (the very large one to the right and the smaller one in the bottom center) that aren't included on the consensus image. Did they have some reason that they didn't make the cut?

This app is brilliant, BTW.

**Comment by ttfnrob** [comment]
Thanks. Well you've hit on the whole point of this app scientifically :)

Yes - that big bubble on the right certainly ought to appear (and does in a nearby image http://mwp-milkman.herokuapp.com/subjects/AMW0002t48). Currently I'm using this app to test out different clustering code and the different parameters for the DBSCAN function I'm using. So for now: this is almost a feature, rather than a bug.

My method right now for generating lists of objects or the whole survey is to check for completed images with objects in (this is a fast process) then DBCAN them all to extract the objects (slower but ok). There will need to be a final, de-duplication step too. In this regard the lack of the big bubble in one image is saved by its appearance in another - but I have to be able to quantify it for any publication.
